config/routes.rb
Propertymanagement::Application.routes.draw do
  resources :user_sessions

  resources :users

  resources :repair_requests

  resources :leases

  resources :units

  resources :properties
  
  root 'users#index'
  
  get "login", :to => "user_sessions#new"
  
  get "logout", :to => "user_sessions#destroy"

end

app/models/repair_request.rb
class RepairRequest < ActiveRecord::Base
  belongs_to :submitter, :class_name => 'User', :foreign_key => 'submitter_id'
  belongs_to :responder, :class_name => 'User', :foreign_key => 'responder_id'
end

app/controllers/repair_requests_controller.rb
class RepairRequestsController < ApplicationController
  before_action :set_repair_request, only: [:show, :edit, :update, :destroy]

  # GET /repair_requests
  # GET /repair_requests.json
  def index
    @repair_requests = RepairRequest.all
  end

  # GET /repair_requests/1
  # GET /repair_requests/1.json
  def show
  end

  # GET /repair_requests/new
  def new
    @repair_request = RepairRequest.new
  end

  # GET /repair_requests/1/edit
  def edit
  end

  # POST /repair_requests
  # POST /repair_requests.json
  def create
    @repair_request = RepairRequest.new(repair_request_params)
    
    set_the_user_id

    respond_to do |format|
      if @repair_request.save
        format.html { redirect_to @repair_request, notice: 'Repair request was successfully created.' }
        format.json { render action: 'show', status: :created, location: @repair_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @repair_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repair_requests/1
  # PATCH/PUT /repair_requests/1.json
  def update
    set_the_user_id
    
    respond_to do |format|
      if @repair_request.update(repair_request_params)
        format.html { redirect_to @repair_request, notice: 'Repair request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @repair_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repair_requests/1
  # DELETE /repair_requests/1.json
  def destroy
    @repair_request.destroy
    respond_to do |format|
      format.html { redirect_to repair_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair_request
      @repair_request = RepairRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_request_params
      params.require(:repair_request).permit(:open_date, :close_date, :request_details, :request_response, :submitter_id, :responder_id)
    end
end

def set_the_user_id
  if current_user.has_role? :renter  and @repair_request.submitter_id == nil
    @repair_request.submitter_id = current_user.id
  elsif current_user.has_role? :renter
    @repair_request.submitter_id = current_user.id
  end
  if current_user.has_role? :manager and @repair_request.submitter_id != nil
    @repair_request.responder_id = current_user.id
  end
end

app/helpers/repair_requests_helper.rb
module RepairRequestsHelper
end

app/views/repair_requests/_form.html.erb
<%= form_for(@repair_request) do |f| %>
  <% if @repair_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair_request.errors.count, "error") %> prohibited this repair_request from being saved:</h2>

      <ul>
      <% @repair_request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <% if current_user %>

  <% if current_user.has_role? :renter and current_user.id == @repair_request.submitter_id or @repair_request.submitter_id == nil %>  
  <div class="field">
    <%= f.label :open_date %><br>
    <%= f.date_select :open_date %>
  </div>
  <% else %>
    <div class="field">
      <%= f.label :open_date %><br>
      <%= f.date_select :open_date, disabled: true %>
    </div>
  <% end %>
  
  <% if current_user.has_role? :manager %>  
  <div class="field">
    <%= f.label :close_date %><br>
    <%= f.date_select :close_date %>
  </div>
  <% else %>
    <div class="field">
      <%= f.label :close_date %><br>
      <%= f.date_select :close_date, disabled: true %>
    </div>  
  <% end %>
  
  <% if current_user.has_role? :renter and current_user.id == @repair_request.submitter_id or @repair_request.submitter_id == nil  %> 
  <div class="field">
    <%= f.label :request_details %><br>
    <%= f.text_area :request_details %>
  </div>
  <% else %>
    <div class="field">
      <%= f.label :request_details %><br>
      <%= f.text_area :request_details, disabled: true %>
    </div>
  <% end %>
  
  <% if current_user.has_role? :manager %>  
  <div class="field">
    <%= f.label :request_response %><br>
    <%= f.text_area :request_response %>
  </div>  
  <% else %>
    <div class="field">
      <%= f.label :request_response %><br>
      <%= f.text_area :request_response, disabled: true %>
    </div>  
  <% end %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>

app/views/repair_requests/edit.html.erb
<h1>Editing repair_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair_request %> |
<%= link_to 'Back', repair_requests_path %>

app/views/repair_requests/index.html.erb
<h1>Listing repair_requests</h1>
  <% if current_user %>  
<table border= 1>
  <thead>
    <tr>
      <th>Open date</th>
      <th>Close date</th>
      <th>Request details</th>
      <th>Request response</th>
      <th>Submitter</th>
      <th>Responder</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
      <tbody>
        <% if current_user.has_role? :manager %>
        <% @repair_requests.each do |repair_request| %>
          <tr>
            <td><%= repair_request.open_date %></td>
            <td><%= repair_request.close_date %></td>
            <td><%= repair_request.request_details %></td>
            <td><%= repair_request.request_response %></td>
            <td><%= repair_request.submitter_id %></td>
            <td><%= repair_request.responder_id %></td>
            <td><%= link_to 'Show', repair_request %></td>
            <td><%= link_to 'Edit', edit_repair_request_path(repair_request) %></td>
            <td><%= link_to 'Destroy', repair_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    <% elsif current_user.has_role? :renter %>
    
    <% @repair_requests.where(['submitter_id = ?', current_user.id]).each do |repair_request| %>
        <tr>
          <td><%= repair_request.open_date %></td>
          <td><%= repair_request.close_date %></td>
          <td><%= repair_request.request_details %></td>
          <td><%= repair_request.request_response %></td>
          <td><%= repair_request.submitter_id %></td>
          <td><%= repair_request.responder_id %></td>
          <td><%= link_to 'Show', repair_request %></td>
          <td><%= link_to 'Edit', edit_repair_request_path(repair_request) %></td>
          <td><%= link_to 'Destroy', repair_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      
    <% end %>  
  <% end %>
  </tbody>
</table>

<br>

  <% if current_user %>  
    <% if current_user.has_role? :renter %>
      <%= link_to 'New Repair request', new_repair_request_path %>
    <% end %>
<% end %>

app/views/repair_requests/new.html.erb
<h1>New repair_request</h1>

<%= render 'form' %>

<%= link_to 'Back', repair_requests_path %>

app/views/repair_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Open date:</strong>
  <%= @repair_request.open_date %>
</p>

<p>
  <strong>Close date:</strong>
  <%= @repair_request.close_date %>
</p>

<p>
  <strong>Request details:</strong>
  <%= @repair_request.request_details %>
</p>

<p>
  <strong>Request response:</strong>
  <%= @repair_request.request_response %>
</p>

<p>
  <strong>Submitter:</strong>
  <%= @repair_request.submitter_id %>
</p>

<p>
  <strong>Responder:</strong>
  <%= @repair_request.responder_id %>
</p>

<%= link_to 'Edit', edit_repair_request_path(@repair_request) %> |
<%= link_to 'Back', repair_requests_path %>