config/routes.rb
Propertymanagement::Application.routes.draw do
  resources :user_sessions

  resources :users

  resources :repair_requests

  resources :leases

  resources :units

  resources :properties
  
  root 'users#index'
  
  get "login", :to => "user_sessions#new"
  
  get "logout", :to => "user_sessions#destroy"

end

app/views/shared/_navigation.html.erb
	<div id="navigation">
		<ul>
			<li><%= link_to('users', root_url) %></li>      
      
      <% if current_user %>      
        <li><%= link_to("Logout", logout_path) %></li>
        <li><%= link_to("edit profile", edit_user_path(current_user.id)) %>
      <% else %>      
        <li><%= link_to("Login", login_path) %></li>
        <li><%= link_to("Create account", new_user_path) %></li>
      <% end %>
      <% if current_user %>
        <li><%= link_to("repair requests", repair_requests_path) %></li>
        <li><%= link_to("leases", leases_path)%>
      <% end %>
		</ul>
	</div>

app/views/shared/_repair_requests_table.html.erb
<tr>
  <td><%= repair_request.open_date %></td>
  <td><%= repair_request.close_date %></td>
  <td><%= repair_request.request_details %></td>
  <td><%= repair_request.request_response %></td>
  <td><%= repair_request.submitter_id %></td>
  <td><%= repair_request.responder_id %></td>
  <td><%= link_to 'Show', repair_request %></td>
  <td><%= link_to 'Edit', edit_repair_request_path(repair_request) %></td>
  <td><%= link_to 'Destroy', repair_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>